
services:
  code_base:
    build: .
    image: ashikzaman43/codebase_diabetesprediction
    volumes:
       - ai_system:/tmp
    command:
    - sh
    - "-c"
    - |
      rm -rf /tmp/codeBase/ && cp -r /codeBase/ /tmp/;
volumes:
  ai_system:
    external: true