FROM busybox
#RUN mkdir -p /knowledgeBase
COPY ./../../images/knowledgeBase_diabetesPrediction/currentOlsSolution.xml /knowledgeBase/
COPY ./../../images/knowledgeBase_diabetesPrediction/currentAiSolution.xml /knowledgeBase/
