services:
  learning_base:
    build: .
    image: ashikzaman43/activationbase_diabetesprediction
    volumes:
       - ai_system:/tmp
    command:
    - sh
    - "-c"
    - |
      rm -rf /tmp/activationBase/ && cp -r /activationBase/ /tmp/;
volumes:
  ai_system:
    external: true