FROM busybox
#RUN mkdir -p /learningBase/train /learningBase/validation
COPY ./../../data/dataset/training_data.csv /learningBase/train/
COPY ./../../data/dataset/test_data.csv /learningBase/validation/
